name: Python Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run unit tests
      run: |
        time python -m unittest tests/test_example.py
